### ISSUE TITLE
请教下如何配置github 授权登录问题

### ISSUE THREAD

**Issue by WangXinis** [Plutoeat/mysite#1]
通过github 授权用户登录问题

**Comment by Plutoeat** [comment]
你的问题是基于[#715](https://github.com/liangliangyy/DjangoBlog/issues/715)，他已经给出了示例给你
http://www.lylinux.net/oauth/authorize?type=github
及源码地址 https://github.com/liangliangyy/DjangoBlog/blob/master/oauth/views.py#L55

**Comment by Plutoeat** [comment]
你的问题是基于[#715](https://github.com/liangliangyy/DjangoBlog/issues/715)，他已经给出了示例给你
http://www.lylinux.net/oauth/authorize?type=github
及源码地址 https://github.com/liangliangyy/DjangoBlog/blob/master/oauth/views.py#L55
